### ISSUE TITLE
verynice bogs down the server after a while

### ISSUE THREAD

**Issue by ZizzyZizzy** [JohannesBuchner/verynice#3]
We've been using this most excellent program for years. I've recently discovered during a troubleshooting session that if you leave it as a long running process, it eventually bogs down the server CPU and the process(es) it is throttling.

Restarting the daemon fixes the issue. Nothing else on the server or the processes being re-niced was changed, but the system load and the process being throttled both immediately go back to normal.

I just ran this on a production server with a process that was re-niced to 38 and a system load of 12. The simple act of restarting the verynice daemon dropped the system load to under 4 and the process that was re-niced to 38 is now only at 22. (java processes, mostly.) After a few minutes, it seems to stabilize again with a system load of between 6-8 and the previous process at a nice of 38 stays at 22 now.

I'm stumped as to why this would happen. I've put in a cron job every 30 minutes to restart the process, which solves my immediate issue.

**Comment by JohannesBuchner** [comment]
Thank you for documenting this here. Be aware that this program was not written by me, but is from  http://www.tam.cornell.edu/~sdh4/verynice/

**Comment by kakra** [comment]
The load probably increases because you're getting more and more waiting processes due to some important processes being too nice. You should not renice processes too much that require a somewhat immediate execution. If these java processes are your main concern, it may even help to give them even slightly more priority instead of less. If the java processes are mainly doing batched processing, you may have a better time simply using `schedtool -B` on them and leave the nice value as is. Batch scheduling gives processes a slight scheduling disadvantage but longer time slices to run, they also stick better to one CPU core while running. This increases CPU cache utilization and should free CPU time for other stuff, thus your load should stay lower.

Also, verynice is problematic with processes spawning children. You should avoid handling such master processes with verynice (which may not always be possible) because it has the tendency of creating a feedback loop of adjusting nice even more down. If your kernel uses process autogrouping (see `/proc/sys/kernel/sched_autogroup_enabled`, if it says 0 or doesn't exist, your kernel does not use autogrouping), then verynice will not work properly at all and only creates bad feedback loops because `verynice` doesn't look at the session ID.

A better indicator would be putting your monitored processes in a cgroup and monitoring its pressure stall information. Then adjust CPU bandwidth or IO/memory shares as required for your processes to meet the expected requirements. This is pretty easy if you're using systemd, and pretty difficult with classic init systems.

Monitoring pressure stall information can look like this:
![image](https://user-images.githubusercontent.com/17684/79636154-f7fe0d00-8175-11ea-969f-ff9ddfad100a.png)

It's usually a much better indicator than loadavg because loadavg only tells you that something was blocked for whatever reason (even processes waiting on other processes) while PSI tells you how long some or all processes had to wait on a ressource. As long as those numbers stay in the nanoseconds or microseconds range, you don't have a load problem even when load may indicate otherwise, loadavg is also a counter (and thus flattens out your real concern) while PSI measures time, compare:
![image](https://user-images.githubusercontent.com/17684/79636237-88d4e880-8176-11ea-8f0e-b8f60df3d013.png)

Take note how the load spikes for some longer periods while PSI indicates there was absolutely no CPU load.

If you're interested, I can send my munin sensors for PSI. They are not finalized, thus I didn't publish them yet.

See-also: https://superuser.com/questions/805599/nice-has-no-effect-in-linux-unless-the-same-shell-is-used
See-also: https://www.kernel.org/doc/html/latest/accounting/psi.html

**Comment by ZizzyZizzy** [comment]
@kakra  Thanks for the in-depth look at this. I've never had the opportunity to deep dive.

Interesting about kernel.sched_autogroup_enabled=0. I'll give that a try! I'm working with single-threaded java processes mostly. Minecraft legacy.

**Comment by kakra** [comment]
Some more tips to reduce load: If that system is running on a hardware RAID or VMware virtualization, you may want to disable IO schedulers (use `noop`). If that doesn't work so well for the latency of your java processes, try `deadline` or `mq-deadline` instead but that usually has the potential for some racing with the hardware queue implementation. Since the java processes may share some identical anonymous memory, you could also use `uksmd` to maybe reduce memory pressure a little (or use the [ksm preloader](https://github.com/unbrice/ksm_preload) on the java processes tho that may do "a little too much"). But my best tip is still: use PSI if your kernel supports it and find the bottlenecks with it, then use cgroups as "nice on steroids" to adjust to the needs of your processes. If you are not able to reduce load that way, your system is probably short of some resource, PSI will tell you which it is.
